version: "3.9"

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/main.py
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  db_postgres_data:
  pip_cache: