version: "3.9"

services:
  db:
    container_name: local-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    volumes:
      - mongodb:/data/db
    ports:
      - 8081:8081

volumes:
  mongodb: