version: "3.9"

services:
  app:
    container_name: app
    image: app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/main.py
    depends_on:
      - db

  db:
    container_name: local-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    volumes:
      - mongodb:/data/db
    ports:
      - 8081:8081

volumes:
  mongodb: